on:
  push:
    branches:
      - main
    paths:
      - "**.csv"
  pull_request:
    branches:
      - main
    paths:
      - "**.csv"
  workflow_dispatch:

jobs:
  create_raid_list_json:
    name: Create the raid list json
    runs-on: windows-latest
    steps:
      - name: First step
        run: .github/scripts/create_raid_list.py
        shell: python
