on:
  push:
    branches:
      - main
    paths:
      - "**.csv"
  pull_request:
    branches:
      - main
    paths:
      - "**.csv"
  workflow_dispatch:

jobs:
  create_raid_list_json_then_export_it:
    name: Create the raid list json then upload it to Filestack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.
      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip requests
          python -m pip install filestack-python
      - name: Finally run the Python file
        run: python .github/scripts/create_raid_list.py
      - name: Commit changes
        run: |
          git config --global user.name "Matrix4348's first workflow"
          git add ./"community-gathered data"/raid_list.json
          git commit --allow-empty -m "Magically create raid_list.json"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload raid_list.json to Filestack
        run: python .github/scripts/upload_raid_list_json_to_Filestack.py
        env:
          app_secret: ${{ secrets.FILESTACK_APP_SECRET }}
          handle: ${{ vars.FILESTACK_FILE_HANDLE }}
